# Generated by Django 4.0.4 on 2022-05-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('reserves', models.IntegerField()),
                ('mined', models.IntegerField()),
                ('residue', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.TextField(max_length=20)),
                ('career', models.TextField(max_length=100)),
                ('stack', models.TextField(max_length=20)),
                ('production_date', models.DateField()),
                ('production_tonnage', models.IntegerField()),
                ('used_tonnage', models.IntegerField(blank=True)),
                ('rest_tonnage', models.IntegerField(blank=True)),
                ('al2o', models.FloatField()),
                ('fe2o3', models.FloatField()),
                ('tio2', models.FloatField()),
                ('sio2', models.FloatField()),
                ('k2o', models.FloatField()),
                ('cao', models.FloatField()),
                ('mgo', models.FloatField(blank=True)),
                ('na2o', models.FloatField(blank=True)),
                ('loi', models.FloatField(blank=True)),
                ('total', models.FloatField()),
                ('carbon', models.FloatField(blank=True)),
                ('rest_on_sieve', models.FloatField(blank=True)),
                ('sulfur', models.FloatField(blank=True)),
                ('plastic', models.FloatField(blank=True)),
                ('fluidity', models.FloatField(blank=True)),
                ('grade', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shipped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.TextField(max_length=200)),
                ('date_of_shipped', models.DateField()),
                ('stack', models.TextField(max_length=20)),
                ('shipped_tonnage', models.IntegerField()),
                ('rest_tonnage', models.IntegerField(blank=True)),
                ('decommissioned', models.IntegerField(blank=True)),
                ('grade', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack', models.TextField(max_length=20)),
                ('career', models.TextField(max_length=100)),
                ('production_tonnage', models.IntegerField()),
                ('used_tonnage', models.IntegerField(blank=True)),
                ('rest_tonnage', models.IntegerField(blank=True)),
                ('al2o', models.FloatField()),
                ('fe2o3', models.FloatField()),
                ('tio2', models.FloatField()),
                ('sio2', models.FloatField()),
                ('k2o', models.FloatField()),
                ('cao', models.FloatField()),
                ('mgo', models.FloatField(blank=True)),
                ('na2o', models.FloatField(blank=True)),
                ('loi', models.FloatField(blank=True)),
                ('total', models.FloatField()),
                ('carbon', models.FloatField(blank=True)),
                ('rest_on_sieve', models.FloatField(blank=True)),
                ('sulfur', models.FloatField(blank=True)),
                ('plastic', models.FloatField(blank=True)),
                ('fluidity', models.FloatField(blank=True)),
                ('grade', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack', models.TextField(max_length=20)),
                ('career', models.TextField(max_length=100)),
                ('date_of_transport', models.DateField()),
                ('transported_tonnage', models.IntegerField()),
                ('destination', models.TextField(max_length=200)),
                ('grade', models.TextField(max_length=20)),
            ],
        ),
    ]
