# Generated by Django 4.0.4 on 2022-06-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samples',
            name='production_date',
            field=models.DateField(blank=True),
        ),
    ]
